### ISSUE TITLE
import error when trying to run metrics studio

### ISSUE THREAD

**Issue by symphorien** [crillab/metrics#9]
```
root@6c9ffdbb37c7:~/metrics# gunicorn metrics.studio.web.application:server  --name metrics --workers 1 --log-level=debug 
[2021-12-06 15:15:17 +0000] [4512] [DEBUG] Current configuration:
  config: None
  bind: ['127.0.0.1:8000']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /root/metrics
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: -
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: metrics
  default_proc_name: metrics.studio.web.application:server
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f08e268b0d0>
  on_reload: <function OnReload.on_reload at 0x7f08e268b1f0>
  when_ready: <function WhenReady.when_ready at 0x7f08e268b310>
  pre_fork: <function Prefork.pre_fork at 0x7f08e268b430>
  post_fork: <function Postfork.post_fork at 0x7f08e268b550>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f08e268b670>
  worker_int: <function WorkerInt.worker_int at 0x7f08e268b790>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f08e268b8b0>
  pre_exec: <function PreExec.pre_exec at 0x7f08e268b9d0>
  pre_request: <function PreRequest.pre_request at 0x7f08e268baf0>
  post_request: <function PostRequest.post_request at 0x7f08e268bb80>
  child_exit: <function ChildExit.child_exit at 0x7f08e268bca0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f08e268bdc0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f08e268bee0>
  on_exit: <function OnExit.on_exit at 0x7f08e2690040>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2021-12-06 15:15:17 +0000] [4512] [INFO] Starting gunicorn 20.0.4
[2021-12-06 15:15:17 +0000] [4512] [DEBUG] Arbiter booted
[2021-12-06 15:15:17 +0000] [4512] [INFO] Listening at: http://127.0.0.1:8000 (4512)
[2021-12-06 15:15:17 +0000] [4512] [INFO] Using worker: sync
[2021-12-06 15:15:17 +0000] [4514] [INFO] Booting worker with pid: 4514
[2021-12-06 15:15:17 +0000] [4512] [DEBUG] 1 workers
[2021-12-06 15:15:17 +0000] [4514] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/metrics/metrics/studio/web/__init__.py", line 25, in <module>
    from metrics.studio.web.application import dash
  File "/root/metrics/metrics/studio/web/application.py", line 34, in <module>
    from metrics.wallet.figure.dynamic_figure import BoxPlotly
ModuleNotFoundError: No module named 'metrics.wallet.figure'
[2021-12-06 15:15:17 +0000] [4514] [INFO] Worker exiting (pid: 4514)
[2021-12-06 15:15:18 +0000] [4512] [INFO] Shutting down: Master
[2021-12-06 15:15:18 +0000] [4512] [INFO] Reason: Worker failed to boot.
```

on ubuntu focal freshly installed with sole pip command run `pip install -r requirements.txt`
tested both on master and v.1.0.7

other way to reproduce:
```
root@6c9ffdbb37c7:~/metrics# python3
Python 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import metrics.studio.web
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/metrics/metrics/studio/web/__init__.py", line 25, in <module>
    from metrics.studio.web.application import dash
  File "/root/metrics/metrics/studio/web/application.py", line 34, in <module>
    from metrics.wallet.figure.dynamic_figure import BoxPlotly
ModuleNotFoundError: No module named 'metrics.wallet.figure'
```

**Comment by thibaultfalque** [comment]
Dear @symphorien, 

We are aware that `metrics-studio` is currently not working. Actually, `metrics-studio` has not been updated since a while, whereas `metrics-wallet` received some updates more recently which explains why the import fails. 

Unfortunately,  this part of metrics has not been officially released (this is why it is not documented). We plan to make a public release of `metrics-studio` next year. 

Until then, you can still use metrics as a library as described in the [documentation](https://metrics.readthedocs.io) and import it in jupyter notebooks for instance, to make your analyses.

**Comment by symphorien** [comment]
thanks for clarifying
